-- =====================================================================
-- RESET TEMPLATES & CREATE JUNCTION TABLE
-- =====================================================================

CREATE TABLE IF NOT EXISTS template_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT REFERENCES templates(id) ON DELETE CASCADE,
    component_id BIGINT REFERENCES components(id) ON DELETE CASCADE,
    qty INT NOT NULL DEFAULT 1
);

-- Hapus data lama
TRUNCATE TABLE template_components CASCADE;
DELETE FROM templates;

-- Masukkan 30 Template Baru
INSERT INTO templates (id, title, estimated_price, description, photo_url, category, updated_at, is_deleted) VALUES
(1, 'Robot Line Follower', 250000, 'Robot pengikut garis hitam menggunakan sensor inframerah.', 'https://placehold.co/400x400/FFF/333.png?text=Line+Follower', 'Robotika', NOW(), false),
(2, 'Smart Home Suhu', 120000, 'Pemantau suhu ruangan via internet.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Home', 'Smart Home', NOW(), false),
(3, 'Kunci Pintu RFID', 200000, 'Buka pintu dengan kartu RFID.', 'https://placehold.co/400x400/FFF/333.png?text=RFID+Lock', 'Keamanan', NOW(), false),
(4, 'Penyiram Tanaman', 180000, 'Penyiram tanaman otomatis saat tanah kering.', 'https://placehold.co/400x400/FFF/333.png?text=Penyiram', 'Agrikultur', NOW(), false),
(5, 'Stasiun Cuaca Mini', 210000, 'Alat pengukur suhu, kelembaban, dan tekanan udara.', 'https://placehold.co/400x400/FFF/333.png?text=Weather+Station', 'Smart Home', NOW(), false),
(6, 'Smart Trash Can', 150000, 'Tempat sampah yang terbuka otomatis saat ada tangan.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Trash', 'Smart Home', NOW(), false),
(7, 'Timbangan Digital', 190000, 'Timbangan digital 5kg dengan layar LCD.', 'https://placehold.co/400x400/FFF/333.png?text=Timbangan', 'Lainnya', NOW(), false),
(8, 'Tracker GPS Kendaraan', 350000, 'Pelacak lokasi kendaraan real-time dengan modul GPS.', 'https://placehold.co/400x400/FFF/333.png?text=GPS+Tracker', 'Kendaraan', NOW(), false),
(9, 'Lampu Tidur Cerdas', 100000, 'Lampu yang otomatis menyala saat gelap.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Lamp', 'Smart Home', NOW(), false),
(10, 'Radar Ultrasonik', 160000, 'Pemindai objek sekitar menggunakan gelombang suara.', 'https://placehold.co/400x400/FFF/333.png?text=Radar', 'Robotika', NOW(), false),
(11, 'Sistem Presensi Sidik Jari', 250000, 'Sistem absensi siswa/karyawan dengan fingerprint.', 'https://placehold.co/400x400/FFF/333.png?text=Fingerprint', 'Keamanan', NOW(), false),
(12, 'Detektor Asap SMS', 320000, 'Alarm kebakaran yang mengirim peringatan via SMS.', 'https://placehold.co/400x400/FFF/333.png?text=Fire+Alarm', 'Keamanan', NOW(), false),
(13, 'Running Text Bluetooth', 220000, 'Papan LED berjalan yang pesannya diubah via Bluetooth.', 'https://placehold.co/400x400/FFF/333.png?text=Running+Text', 'Display', NOW(), false),
(14, 'Penetas Telur Otomatis', 180000, 'Inkubator dengan pengatur suhu presisi tinggi.', 'https://placehold.co/400x400/FFF/333.png?text=Inkubator', 'Agrikultur', NOW(), false),
(15, 'Sistem Parkir Otomatis', 210000, 'Palang pintu parkir dengan sensor dan layar.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Parking', 'Lainnya', NOW(), false),
(16, 'Robot Penghindar Rintangan', 230000, 'Robot beroda yang bisa belok sendiri jika ada tembok.', 'https://placehold.co/400x400/FFF/333.png?text=Robot+Avoider', 'Robotika', NOW(), false),
(17, 'Kontrol Peralatan via WiFi', 130000, 'Nyalakan dan matikan lampu rumah dari jarak jauh.', 'https://placehold.co/400x400/FFF/333.png?text=WiFi+Switch', 'Smart Home', NOW(), false),
(18, 'Pengukur Jarak Digital', 90000, 'Meteran elektronik dengan display.', 'https://placehold.co/400x400/FFF/333.png?text=Meteran', 'Lainnya', NOW(), false),
(19, 'Monitor Kualitas Udara', 170000, 'Mendeteksi tingkat polusi dan gas berbahaya.', 'https://placehold.co/400x400/FFF/333.png?text=Air+Quality', 'Kesehatan', NOW(), false),
(20, 'Alat Hitung Pengunjung', 140000, 'Menghitung jumlah orang yang masuk ruangan.', 'https://placehold.co/400x400/FFF/333.png?text=People+Counter', 'Lainnya', NOW(), false),
(21, 'Smart Aquarium', 260000, 'Penguras dan pengisi air aquarium otomatis.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Aquarium', 'Smart Home', NOW(), false),
(22, 'Sistem Peringatan Banjir', 160000, 'Deteksi level air sungai dan alarm banjir.', 'https://placehold.co/400x400/FFF/333.png?text=Flood+Warning', 'Lingkungan', NOW(), false),
(23, 'Kipas Angin Suhu Otomatis', 120000, 'Kipas menyala sesuai suhu ruangan.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Fan', 'Smart Home', NOW(), false),
(24, 'Bel Pintu Kamera (Dummy)', 280000, 'Prototipe bel pintu cerdas dengan ESP32-CAM.', 'https://placehold.co/400x400/FFF/333.png?text=Smart+Bell', 'Keamanan', NOW(), false),
(25, 'Monitoring Daya Listrik', 190000, 'Melihat penggunaan Watt peralatan rumah tangga.', 'https://placehold.co/400x400/FFF/333.png?text=Power+Monitor', 'Smart Home', NOW(), false),
(26, 'Robot Tangan Remote', 350000, 'Kendali lengan robot menggunakan sensor sudut.', 'https://placehold.co/400x400/FFF/333.png?text=Robot+Arm', 'Robotika', NOW(), false),
(27, 'Data Logger Suhu MicroSD', 150000, 'Merekam perubahan suhu seharian ke memori.', 'https://placehold.co/400x400/FFF/333.png?text=Data+Logger', 'Lainnya', NOW(), false),
(28, 'Sistem Telemetri LoRa', 400000, 'Kirim data sensor sejauh 5KM tanpa internet.', 'https://placehold.co/400x400/FFF/333.png?text=LoRa+Telemetry', 'Komunikasi', NOW(), false),
(29, 'Gembok Laci Ketukan', 110000, 'Buka laci dengan pola ketukan rahasia.', 'https://placehold.co/400x400/FFF/333.png?text=Knock+Lock', 'Keamanan', NOW(), false),
(30, 'Jam Digital OLED', 130000, 'Jam presisi tinggi dengan modul RTC.', 'https://placehold.co/400x400/FFF/333.png?text=Digital+Clock', 'Display', NOW(), false);

-- Map Komponen
INSERT INTO template_components (template_id, component_id, qty) VALUES

(1, 1, 1), (1, 27, 2), (1, 39, 2), (1, 41, 1), (1, 70, 2), (1, 67, 1), (1, 69, 1),
(2, 7, 1), (2, 15, 1), (2, 66, 1), (2, 67, 1),
(3, 2, 1), (3, 32, 1), (3, 48, 1), (3, 44, 1), (3, 49, 1), (3, 68, 1),
(4, 7, 1), (4, 23, 1), (4, 47, 1), (4, 44, 1), (4, 68, 1),
(5, 1, 1), (5, 18, 1), (5, 61, 1), (5, 68, 1),
(6, 1, 1), (6, 13, 1), (6, 37, 1), (6, 70, 1),
(7, 7, 1), (7, 31, 1), (7, 59, 1), (7, 60, 1),
(8, 5, 1), (8, 34, 1), (8, 55, 1), (8, 73, 1),
(9, 8, 1), (9, 20, 1), (9, 44, 1),
(10, 1, 1), (10, 13, 1), (10, 37, 1), (10, 59, 1), (10, 60, 1),
(11, 7, 1), (11, 33, 1), (11, 61, 1), (11, 49, 1),
(12, 1, 1), (12, 21, 1), (12, 55, 1), (12, 49, 1),
(13, 1, 1), (13, 65, 1), (13, 51, 1),
(14, 7, 1), (14, 15, 1), (14, 45, 1), (14, 39, 1),
(15, 1, 1), (15, 13, 1), (15, 37, 1), (15, 59, 1), (15, 60, 1),
(16, 1, 1), (16, 13, 1), (16, 39, 2), (16, 42, 1),
(17, 8, 1), (17, 45, 1),
(18, 1, 1), (18, 13, 1), (18, 61, 1),
(19, 5, 1), (19, 22, 1), (19, 18, 1), (19, 61, 1),
(20, 1, 1), (20, 26, 1), (20, 63, 1),
(21, 7, 1), (21, 23, 1), (21, 47, 2), (21, 45, 1),
(22, 1, 1), (22, 24, 1), (22, 55, 1),
(23, 1, 1), (23, 14, 1), (23, 44, 1),
(24, 6, 1), (24, 49, 1), (24, 78, 1),
(25, 7, 1), (25, 30, 1), (25, 61, 1),
(26, 1, 1), (26, 79, 1), (26, 38, 4),
(27, 1, 1), (27, 16, 1), (27, 36, 1), (27, 35, 1),
(28, 4, 1), (28, 54, 1), (28, 18, 1), (28, 70, 1),
(29, 2, 1), (29, 48, 1), (29, 49, 1), (29, 44, 1),
(30, 1, 1), (30, 35, 1), (30, 65, 1);
